# Generated by Django 3.1.1 on 2020-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20200918_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='duration',
            field=models.IntegerField(choices=[(0, 'once'), (1, 'repeating'), (2, 'forever')], default=0),
        ),
        migrations.AddField(
            model_name='coupons',
            name='duration_months',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
