# Generated by Django 3.1.1 on 2020-09-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20200920_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='membership',
            new_name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_subscription_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.customer'),
        ),
    ]
