# Generated by Django 3.1.1 on 2020-09-22 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auto_20200921_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripeid',
            new_name='stripe_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='current_period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
