# Generated by Django 3.1.1 on 2020-09-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_auto_20200922_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscription_active',
        ),
    ]
