# Generated by Django 3.1.1 on 2020-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_remove_customer_subscription_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name_plural': 'coupons'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
