# Generated by Django 3.1.1 on 2020-09-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20200924_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
