# Generated by Django 3.1.1 on 2020-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_cancelsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelsurvey',
            name='primary_reason',
            field=models.IntegerField(choices=[(0, 'No longer needed it'), (1, "It didn't meet my needs"), (2, 'Found an alternative'), (3, 'Quality was less than expected'), (4, 'Ease of use was less than expected'), (5, 'Access to the service was less than expected'), (6, 'Customer service was less than expected'), (7, 'Other')]),
        ),
    ]
