# Generated by Django 3.1.1 on 2020-09-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(default='blog/images/readingwithkids.jpg', upload_to='blog/images'),
        ),
    ]
