# Generated by Django 3.1.1 on 2021-01-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210103_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_parsed',
            field=models.TextField(default=''),
        ),
    ]
