# Generated by Django 3.1.1 on 2021-01-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_content_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_parsed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
