# Generated by Django 3.1.1 on 2021-01-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210104_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='url',
            field=models.URLField(blank=True, default='', editable=False),
        ),
    ]
