# Generated by Django 3.1.1 on 2020-09-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watched',
            options={'verbose_name_plural': 'watched'},
        ),
    ]
