# Generated by Django 3.1.1 on 2020-10-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0003_video_free_to_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
