# Generated by Django 3.1.1 on 2020-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0004_auto_20201001_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
