# Generated by Django 3.1.1 on 2020-10-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0006_remove_video_order_number'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='video',
            order_with_respect_to='course',
        ),
    ]
