# Generated by Django 3.1.1 on 2020-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0007_auto_20201005_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')], default=0),
        ),
    ]
