# Generated by Django 3.1.1 on 2020-11-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0009_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.DurationField(),
        ),
    ]
