# Generated by Django 3.1.1 on 2020-11-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0010_auto_20201114_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='activity_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
